---
- hosts: localhost
  become: true
  connection: local

  pre_tasks:
  - name: update repos.
    ansible.builtin.package:
      update_cache: yes
    changed_when: false

  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: mc,tree,nmap,neofetch, mtr,htop,zsh,cmatrix,rclone,samba,syncthing
      state: latest
      
