---
- hosts: localhost
  become: true
  connection: local

  pre_tasks:
  - name: update repos.
    ansible.builtin.package:
      update_cache: yes
    changed_when: false

  tasks:
    - import_tasks: tasks/packages.yml  
